Sorting
mgunyho/tere pull request #64
Opened 2022-09-17 02:46 UTC by joshrdane

**Sorting Options**
- Name (default) `--sort name`
- Most recently accessed date `--sort adate`
- Most recently created date `--sort cdate`
- Most recently modified date `--sort mdate`

**Notes**
- `alt-s` cycles the sorting type
- Setting the sort flag only sets the starting sorting method. 
- As of right now, history does not keep track of which sorting method was used last. 
- There is not currently a column displaying the dates associated with the sorting methods when sorting is done by date. 
- The sorting method is shown in the footer as `sort:<type>`.

2022-09-17 03:41 UTC, mgunyho commented
Thanks! I'm busy this weekend but I'll take a look early next week.

As a quick note, `--sort X` is kind of inconsistent with other similar "cyclable" options (like e.g. case sensitive mode), but I think this is definitely the right way to do it. I'm not sure why I did it the other way with the others tbh, I should think about that again.

2022-09-22 20:10 UTC, mgunyho requested changes
Sorry for the delay! This looks pretty good, the review comments are mostly cosmetic. Some general comments:

- After merging #62, `app_state.settings` has to be changed to `app_state.settings()` everywhere, sorry about that.
- The search state is not correctly preserved when changing the sort mode, see gif below. Try to add a setter for the sort mode in `app_state` and use `with_cursor_fixed_at_current_item` like `set_filter_search` does (added in #62). Please add some simple tests to `app_state` to make sure that it works correctly.
- The info bar is getting quite crowded. For example in a folder with >100 files, having a terminal window with 70 characters (surprisingly common occurrence on my tiny laptop screen) and sorting by e.g. "accessed", the search overlaps with the info message even with a single character. I can try to squeeze it a bit after this is merged, but it has to be definitely done before the next release.
- I'm not entirely happy that we don't show the thing we're sorting by, but we can leave that for later (I think it would need a column header).


[sorting-search-not-updated2.webm](https://user-images.githubusercontent.com/20118130/191841296-25057d55-eec2-4833-a836-bfef15a161b2.webm)

2022-09-22 23:54 UTC, joshrdane commented
Yeah, the column header is something that we can put in there and that would also free up the area I allocated for sorting in the footer. I will take some time this weekend to address the issues in the comments.

2022-09-22 23:59 UTC, joshrdane commented on src/app_state.rs
> +                            b.accessed().partial_cmp(&a.accessed()).unwrap()
I agree. I also was not 100% on whether we should be sorting ASC or DSC or if we wanted that to be another feature added.

2022-09-28 16:58 UTC, joshrdane reviewed
I implemented everything except tests for the sorting mode based on date, I am having trouble getting the tests to populate times for the CustomDirEntries.

2022-09-29 16:56 UTC, mgunyho commented
Merging the master made the diff a bit harder to interpret, I'll do a rebase on to develop.

2022-09-29 18:57 UTC, mgunyho commented
Oops, that turned out to be a bit trickier than I thought. I cleaned up the version history a bit, split some things off into separate commits and removed some unnecessary ones (like importing intrinsics::unreachable and then removing the import). You will need to do `git fetch` and then `git reset --hard origin/sorting` to have your local version match up with this one, just make sure that you don't lose any work. I won't have time to do the review anymore today, but I'll get back to it soon.

2022-09-29 19:00 UTC, mgunyho commented
Ah, one more thing that is missing: the new feature should be mentioned in the changelog, and also the keyboard shortcut and CLI option should be documented in the readme (there is a test to check that all default shortcuts are listed).

2022-10-04 18:51 UTC, mgunyho reviewed
So this looks pretty good. The following things are left:
- Should we leave out the option to sort by `accessed`? I'm a bit inclined towards yes.
- The README should mention the `--sort` CLI option, as well as the default keyboard shortcut and the `ChangeSortMode` action
- The CHANGELOG should mention this feature under v 1.3.0

I can make the changes to the readme and the changelog if you want.

2022-10-04 18:56 UTC, mgunyho commented
Oh yeah and also I tried to create some unit tests for this, but you're right, modifying the timestamp of a `Metadata` is not really possible, and `update_ls_output_buf` is hardcoded to read the current folder, which you can't really change inside a test... so let's just rely on manual testing for now.

2022-10-06 05:25 UTC, mgunyho commented on src/app_state.rs
> +    }
Hmm, according to [this documentation](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/ns-fileapi-win32_file_attribute_data), the accessed time on Windows doesn't contain the time of day, just the date. So it's quite inconsistent across platforms, and not a very meaningful thing to sort by. Now I'm definitely convinced that we should remove it.

2022-10-06 21:17 UTC, joshrdane commented on src/app_state.rs
> +    }
I agree. I will remove it on my next push.

2022-10-07 04:34 UTC, mgunyho commented on src/app_state.rs
> +            self_.advance_search("");
I tried to add a separate method for sorting yesterday, but that wasn't really easy either, updating the `ls_output_buf` is quite a tangled mess. I should clean it up a bit, but that's for later.

Changing this line from `self_.advance_search("")` to `self_.update_search_matches()` seems to work and avoids doing some extra stuff. Interesgingly, it doesn't work for `set_case_sensitive` and `set_gap_search` above. But anyway, I think `update_search_matches` is good here.

2022-10-07 05:20 UTC, mgunyho commented on src/settings.rs
> +            SortMode::Name         => "name",
```suggestion
            SortMode::Name => "name",
```

2022-10-12 04:51 UTC, mgunyho commented
I went ahead and implemented these fixes myself, I hope you don't mind.

I'll do another rebase and then merge this.

2022-10-12 05:11 UTC, merged

2022-10-12 05:11 UTC, mgunyho commented
Thanks a lot!